### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by alex000090** [ubports-santoni/projectmanagement#26]
Dear Danct12,
Many thanks for your work!
I'm wery sorry do stupid questions.
At first, why you deal with Ubuntu now instad Sailfish? Are there some features with Ubuntu?
The second, could you write a short instructionhow I can get (or make) image files to install newest Ubuntu?

**Comment by asriel-danctnix** [comment]
Unfortunately it's just that we preferred Ubuntu Touch more than SailfishOS due to it's open environment.

Installation guide can be found here: http://docs.ubports.com/en/latest/porting/installing-16-04.html

In the future, we may not need this due to it being a community port.

**Comment by asriel-danctnix** [comment]
Unfortunately it's just that we preferred Ubuntu Touch more than SailfishOS due to it's open environment.

Installation guide can be found here: http://docs.ubports.com/en/latest/porting/installing-16-04.html

In the future, we may not need this due to it being a community port.

**P.S: He (Danct12) may not be able to answer to your questions as he's currently busy on PinePhone.**

**Comment by alex000090** [comment]
Dear Asriel, thanks for your answer!
I don't use github in regular and I have found "actions" with built images just now. :)
Thanks for the link!
About sailfish. Have you stoped at 3.0.3.10 version or there is newest version?

**Comment by Danct12** [comment]
Since 2020/10/28, Redmi 4X has been added to UBports installer.

Please download the latest version of [UBports installer](https://github.com/ubports/ubports-installer/releases) and install it. You'll need to check "Wipe userdata" in the installer if you're from Android OS.
