### ISSUE TITLE
[LOCATION] GPS doesn't work

### ISSUE THREAD

**Issue by Danct12** [ubports-santoni/projectmanagement#5]
When testing using Pure Maps, the location is somewhere in the ocean..

SensorStatus app reports that it doesn't have any access to the GPS, despite test_gps and logcat shows activity of the GPS.

**Comment by Danct12** [comment]
@keep37 reported that the GPS works fine after wiping dalvik,data,cache,system. tested with unav.

however i haven't tested it yet, will report

**Comment by aceclan** [comment]
Working with unav.
You should not  rotate the phone :) because the map displaying image layer will broken.
 
![screenshot20200307_000515625](https://user-images.githubusercontent.com/31694493/76126660-5af17580-6008-11ea-8c82-8259cfe2439e.png)
![screenshot20200307_000524146](https://user-images.githubusercontent.com/31694493/76126662-5c22a280-6008-11ea-8683-ccaaaa67f11c.png)
![screenshot20200307_000344398](https://user-images.githubusercontent.com/31694493/76126687-78beda80-6008-11ea-9145-9b51d4e7af4a.png)

**Comment by Danct12** [comment]
Sounds like app bug to me, you can report uNav bugs here: https://github.com/costales/unav/issues
